//
//  MentorsScreenInteractor.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MentorsScreenBusinessLogic {
    func loadMentors()
}

protocol MentorsScreenDataStore {
    //var name: String { get set }
}

class MentorsScreenInteractor: MentorsScreenBusinessLogic, MentorsScreenDataStore {
    
    var presenter: MentorsScreenPresentationLogic?
    var worker: MentorsScreenWorker?
    
    // MARK: Do something
    
    func loadMentors() {
        worker = MentorsScreenWorker()
        worker?.getMentorsList(completionn: { mentorsArray in
            //если успешно получены данные
            let response = MentorsScreen.ShowMentorCells.Response(mentorCellsData: mentorsArray)
            self.presenter?.presentMentors(response: response)
        }, error: {
            //если получили ошибку
            print("Error")
        })

    }
}
