//
//  DetailedMentorPresenter.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 29.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedMentorPresentationLogic {
    func presentMentorInfo(response: DetailedMentor.ShowMentorInfo.Response)
    func presentReportStatus(response: DetailedMentor.SendMentorReport.Response)
}

class DetailedMentorPresenter: DetailedMentorPresentationLogic {
    
    weak var viewController: DetailedMentorDisplayLogic?
    
    // MARK: Do something
    
    func presentMentorInfo(response: DetailedMentor.ShowMentorInfo.Response) {
        var viewModel = DetailedMentor.ShowMentorInfo.ViewModel()
        viewModel.name = response.name
        viewModel.discription = response.discription
        viewModel.imageData = response.imageData
        viewModel.languages = response.languages
        viewModel.messageLink = response.messageLink
        viewModel.shortDiscription = response.shortDiscription
        viewController?.showMentorInfo(viewModel: viewModel)
    }
    
    func presentReportStatus(response: DetailedMentor.SendMentorReport.Response) {
        let viewModel = DetailedMentor.SendMentorReport.ViewModel(isReportSucssfulSent: response.isReportSucssfulSent)
        viewController?.isReportSucssfulSentAlert(viewModel: viewModel)
    }
}
