//
//  DetailedMentorModels.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 29.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
struct DetailedMentorCellModel{
    let name: String?
    let discription: String?
    let imageData: Data?
    let languages: [Language]
}
enum DetailedMentor {
    // MARK: Use cases
    
    enum ShowMentorInfo {
        struct Request {
        }
        
        struct Response {
            var name: String?
            var discription: String?
            var imageData: Data?
            var languages: [Language] = []
            var messageLink: String?
            var shortDiscription: String?
            var ShortUUID: String?
        }
        
        struct ViewModel {
            var name: String?
            var discription: String?
            var imageData: Data?
            var languages: [Language] = []
            var messageLink: String?
            var shortDiscription: String?
            var ShortUUID: String?
        }
    }
    
    
    enum SendMentorReport{
        struct Request{
            var reason: String?
        }
        struct Response{
            var isReportSucssfulSent: Bool?
        }
        
        struct ViewModel{
            var isReportSucssfulSent: Bool?
        }
        
    }
}
