//
//  ProfileScreenRouter.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileScreenRoutingLogic {
    func navigateToSingInViewController(source: ProfileScreenViewController, destination: SignInWithAppleViewController)
    func navigateToFillDataViewController(source: ProfileScreenViewController, destination: FillDataViewController)
    func navigateToEditDataViewController(source: ProfileScreenViewController, destination: FillDataViewController, withData: ProfileScreen.loadYourDataa.ViewModel)
    func navigateToStatisticsScreen(source: ProfileScreenViewController, destination: StatisticsViewController)

}

protocol ProfileScreenDataPassing {
    var dataStore: ProfileScreenDataStore? { get }
}

class ProfileScreenRouter: NSObject, ProfileScreenRoutingLogic, ProfileScreenDataPassing {
    
    weak var viewController: ProfileScreenViewController?
    var dataStore: ProfileScreenDataStore?
    
    //MARK: Navigation
    
    func navigateToSingInViewController(source: ProfileScreenViewController, destination: SignInWithAppleViewController) {
        source.show(destination, sender: nil)
    }
    func navigateToFillDataViewController(source: ProfileScreenViewController, destination: FillDataViewController) {
        source.show(destination, sender: nil)
    }
    func navigateToEditDataViewController(source: ProfileScreenViewController, destination: FillDataViewController, withData: ProfileScreen.loadYourDataa.ViewModel) {
       
        guard var detailDS = destination.router?.dataStore else {return}
        passDataToEditDataScreen(source: withData, destination: &detailDS)
        destination.isBackButtonHidden = false
        destination.isItDataEditingScreen = true
        source.show(destination, sender: nil)
    }
    func navigateToStatisticsScreen(source: ProfileScreenViewController, destination: StatisticsViewController){
        source.show(destination, sender: nil)
    }
    // MARK: Passing data
    func passDataToEditDataScreen(source: ProfileScreen.loadYourDataa.ViewModel, destination: inout FillDataDataStore) {
        destination.name = source.name
        destination.languages = source.languages
        destination.shortDiscription = source.shortDiscription
        destination.discription = source.discription
        destination.messageLink = source.messageLink
        destination.imageData = source.imageData
    }
}
