//
//  ProfileScreenPresenter.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileScreenPresentationLogic {
    func presentAuthOrFillDataViewController(response: ProfileScreen.chekcAuthAndDataFill.Response)
    func showYourData(response: ProfileScreen.loadYourDataa.Response)
    func accountDeleted()
    func accountMentoringStatusChanges(response: ProfileScreen.ChangeMentoringStatus.Response)
}

class ProfileScreenPresenter: ProfileScreenPresentationLogic {
    
    func showYourData(response: ProfileScreen.loadYourDataa.Response) {
        var viewModel = ProfileScreen.loadYourDataa.ViewModel()
        viewModel.imageData = response.imageData
        viewModel.messageLink = response.messageLink
        viewModel.name = response.name
        viewModel.languages = response.languages
        viewModel.discription = response.discription
        viewModel.shortDiscription = response.shortDiscription
        viewModel.isMentoring = response.isMentoring
        viewController?.loadYourInfo(viewModel: viewModel)
    }
    
    
    weak var viewController: ProfileScreenDisplayLogic?
    
    // MARK: Do something
    func presentAuthOrFillDataViewController(response: ProfileScreen.chekcAuthAndDataFill.Response) {
        var viewModel: ProfileScreen.chekcAuthAndDataFill.ViewModel?
        if response.isSignedInWithApple == false {
            viewModel = ProfileScreen.chekcAuthAndDataFill.ViewModel(viewControllerWeNeedToShow: SignInWithAppleViewController())
        }
        else if response.isYourInfoFilled == false {
            viewModel = ProfileScreen.chekcAuthAndDataFill.ViewModel(viewControllerWeNeedToShow: FillDataViewController())
        }
        viewController?.showAuthOrFillInfoScreen(viewModel: viewModel)
    }
    
    
    func accountDeleted() {
        viewController?.accountDeleted()
    }
    
    func accountMentoringStatusChanges(response: ProfileScreen.ChangeMentoringStatus.Response) {
        guard let to = response.changedTo else {return}
        let viewModel = ProfileScreen.ChangeMentoringStatus.ViewModel(changedTo: to)
        viewController?.accountMentoringStatusChanges(viewModel: viewModel)
    }
}
