//
//  ProfileScreenWorker.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase
import FirebaseFirestore
import FirebaseStorage

class ProfileScreenWorker {
    func loadYourData(completion: @escaping (ProfileScreen.loadYourDataa.Response) -> (), error: @escaping () -> ()){
        
        guard let urID = Defaults.getShortUUID() else {error();return}
        let ref = Firestore.firestore().collection("Mentors").document(urID)
        
        ref.getDocument { doc, err in
            guard err == nil else {error(); return}
            guard let document = doc else {error(); return}
            
            guard let data = document.data() else {error(); return}
            
            let name = data["Name"] as? String
            let description = data["Description"] as? String
            let shortDescription = document["ShortDescription"] as? String
            let messageLink = data["MessageLink"] as? String
            let appleUUID = data["AppleUUID"] as? String
            let isMentoring = data["IsMentoring"] as? Bool
            let languages = data["Languages"] as? [String]
            
            let languagesAsEnum = LanguageNameToEnumType.from(languages ?? [])
            

            FirebaseImageService.loadImage(userID: appleUUID ?? "") { imgData in
                let response: ProfileScreen.loadYourDataa.Response =  ProfileScreen.loadYourDataa.Response(name: name, discription: description, imageData: imgData, languages: languagesAsEnum, messageLink: messageLink, shortDiscription: shortDescription, isMentoring: isMentoring)
                completion(response)
            }
            
        }
    }
    
    
//    private func loadImage(userID: String, completion: @escaping (Data?) -> ()){
//        let ref = Storage.storage().reference().child("avatars").child(userID)
//        ref.getData(maxSize: 1024 * 1024 * 2) { data, error in
//            guard error == nil else {return}
//            guard let imageData = data else {return}
//            completion(imageData)
//        }
//    }
}

class ChangeMentoringStatusWorker{
    func change(completion: @escaping (_ changedTo: Bool) -> ()) {
        guard let id = Defaults.getShortUUID() else {return}
        let ref = Firestore.firestore().collection("Mentors").document(id)
        
        ref.getDocument { document, err in
            guard err == nil else {return}
            
            let isMentoring = document?.get("IsMentoring") as? Bool?
            
            if isMentoring == true || isMentoring == nil {
                ref.setData(["IsMentoring": false], merge: true)
            } else{
                ref.setData(["IsMentoring": true], merge: true)
            }
        }

    }
}

class DeleteAccountWorker{
    func delete(completion: @escaping () -> ()){
        guard let id = Defaults.getShortUUID() else {return}
        let ref = Firestore.firestore().collection("Mentors").document(id)
        ref.delete(){_ in
            Defaults.write(value: false, forKey: .isSignedInWithApple)
            Defaults.write(value: false, forKey: .isInfoFilled)
            completion()
        }
    }
}
