//
//  ProfileScreenModels.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProfileScreen {
    // MARK: Use cases
    
    enum chekcAuthAndDataFill {
        struct Response {
            var isSignedInWithApple: Bool?
            var isYourInfoFilled: Bool?
        }
        
        struct ViewModel {
            var viewControllerWeNeedToShow: UIViewController
        }
    }
    
    enum loadYourDataa{
        struct Response {
            var name: String?
            var discription: String?
            var imageData: Data?
            var languages: [Language] = []
            var messageLink: String?
            var shortDiscription: String?
            var isMentoring: Bool?
        }
        
        struct ViewModel {
            var name: String?
            var discription: String?
            var imageData: Data?
            var languages: [Language] = []
            var messageLink: String?
            var shortDiscription: String?
            var isMentoring: Bool?
        }
    }
    
    enum ChangeMentoringStatus{
        struct Response{
            var changedTo: Bool?
        }
        struct ViewModel{
            var changedTo: Bool?
        }
    }
}
