//
//  FillDataInteractor.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 30.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FillDataBusinessLogic {
    func loadInfoToFirebase(request: FillData.LoadDataOnServer.Request)
    func getYourInfo()
}

protocol FillDataDataStore {
    var name: String? {get set}
    var discription: String? {get set}
    var imageData: Data? {get set}
    var languages: [Language] {get set}
    var messageLink: String? {get set}
    var shortDiscription: String? {get set}
}

class FillDataInteractor: FillDataBusinessLogic, FillDataDataStore {
    var name: String?
    var discription: String?
    var imageData: Data?
    var languages: [Language] = []
    var messageLink: String?
    var shortDiscription: String?
    
    
    var presenter: FillDataPresentationLogic?
    var worker: FillDataWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func loadInfoToFirebase(request: FillData.LoadDataOnServer.Request) {
        let name = request.name
        let discription = request.discription
        let shortDescription = request.shortDiscription
        let imageData = request.imageData
        let languages = request.languages
        let messageLink = request.messageLink
        
        worker = FillDataWorker()
        worker?.loadToFirebase(name: name, description: discription, imageData: imageData, languages: languages, messageLink: messageLink, shortDescription: shortDescription, completion: {
            let response = FillData.LoadDataOnServer.Response(isSuccesed: true)
            self.presenter?.presentIsSuccessed(response: response)
            Defaults.write(value: true, forKey: .isInfoFilled)

        }, error: {
            let response = FillData.LoadDataOnServer.Response(isSuccesed: false)
            self.presenter?.presentIsSuccessed(response: response)
        })

    }
    func getYourInfo(){
        let response = FillData.TransferDataFromProfileToEditScreen.Response(name: name, discription: discription, imageData: imageData, languages: languages, messageLink: messageLink, shortDiscription: shortDiscription)

        self.presenter?.presentYourData(response: response)
        print(response)
    }

    
}
