//
//  StatisticsModels.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 28.10.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Statistics {
    // MARK: Use cases
    
    enum LoadStats {
        struct Response {
            var numberOfProfileViews: Int?
            var numberOfClickThroughs: Int?
        }
        
        struct ViewModel {
            var numberOfProfileViews: Int?
            var numberOfClickThroughs: Int?
        }
    }
}



enum StatisticsEnum: String, CaseIterable{
    case numberOfClickThroughs = "Клики по ссылке"
    case numberOfProfileViews = "Просмотр профиля"
}
