//
//  StatisticsViewController.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 28.10.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatisticsDisplayLogic: AnyObject {
    func displayStats(viewModel: Statistics.LoadStats.ViewModel)
}

class StatisticsViewController: UIViewController, StatisticsDisplayLogic {

    
    var interactor: StatisticsBusinessLogic?
    var router: (NSObjectProtocol & StatisticsRoutingLogic & StatisticsDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        StatisticsConfigurator.shared.configure(with: self)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        StatisticsConfigurator.shared.configure(with: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Статистика"
        loadStats()
    }
    
    // MARK: - InteractorTasks
    
    func loadStats() {
        interactor?.loadStats()
    }
    // MARK: - PresenterTasks

    func displayStats(viewModel: Statistics.LoadStats.ViewModel) {
        
    }
    
    
}
