//
//  SighInWithAppleRouter.swift
//  ITmentors
//
//  Created by Alexey Vadimovich on 21.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AuthenticationServices

@objc protocol SignInWithAppleRoutingLogic {
    func navigateToSomewhere(source: SignInWithAppleViewController, destination: FillDataViewController)
}

protocol SignInWithAppleDataPassing {
    var dataStore: SignInWithAppleDataStore? { get }
}

class SignInWithAppleRouter: NSObject, SignInWithAppleRoutingLogic, SignInWithAppleDataPassing {
    
    weak var viewController: SignInWithAppleViewController?
    var dataStore: SignInWithAppleDataStore?
    
    func navigateToSomewhere(source: SignInWithAppleViewController, destination: FillDataViewController) {
        destination.isBackButtonHidden = true
        source.show(destination, sender: self)

    }
    
    // MARK: Passing data
    
//    func passDataToNextAuthScreen(destination: inout FillInfoDataStore, withCreds: ASAuthorizationAppleIDCredential) {
//        destination.name = withCreds.fullName?.givenName
//        destination.surname = withCreds.fullName?.familyName
//
//    }
}
